#
# This script illustrates how to take a set of 2D slices stored in a collection of files (PNG in this case)
# and package them into a 3D volume image (a Nifti file format in this case). An Affine registration will
# be performed between every slice and the next one.
#
# The AffineImageReconstruction executable is build out of the source code in the following repository
#
#      https://github.com/INCF/ImageReconstruction
#
#

./AffineImageReconstruction "/WHS/Slices/canon_hist_%03d.png" 125 511 0.5 0.5 0.5 /tmp/canon_hist.nii.gz

#
#  In this particular case, we are using a "placebo" input data set that was generated by
#  expanding the canon_hist.nii.gz file (the histological atlas of the WHS collection).
#  Therefore the slices are already naturally aligned, and should be perfect input to test
#  the functionality of stacking a set of 2D slices into a 3D volume dataset. The output
#  of the command above should simply reproduce the original canon_hist.nii.gz dataset.
#
